version: "3.4"

volumes:
    postgres_data:

services:
    elasticsearch:
        build:
            context: ./
            dockerfile: ./docker/elasticsearch/Dockerfile
        ports:
            - "9200:9200"
            - "9300:9300"

    postgres:
        image: postgres:10.3
        restart: always
        volumes:
            - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: cfpb
            POSTGRES_PASSWORD: cfpb
            POSTGRES_DB: cfgov

    python2:
        build:
            context: .
            dockerfile: Dockerfile
            target: cfgov-develop
            args:
                scl_python_version: python27
        environment:
            # Django migrations run at container start with CFGOV_AUTO_INIT_DB=ON
            AUTO_INIT_DB: ${CFGOV_AUTO_INIT_DB:-OFF}
        ports:
            - "8000:8000"
        volumes:
            - ./:/src/cfgov-refresh
            - ./develop-apps:/src/develop-apps
        depends_on:
            - elasticsearch
            - postgres
        stdin_open: true
        tty: true

    python3:
        build:
            context: .
            dockerfile: Dockerfile
            target: cfgov-develop
            args:
                scl_python_version: rh-python36
        environment:
            # Hardcoded to OFF so only one container runs Django migrations
            AUTO_INIT_DB: 'OFF'
        ports:
            - "8333:8000"
        volumes:
            - ./:/src/cfgov-refresh
            - ./develop-apps:/src/develop-apps
        depends_on:
            - elasticsearch
            - postgres
        stdin_open: true
        tty: true

    docs:
        build:
            context: ./
            dockerfile: ./docker/docs/Dockerfile
        ports:
            - "8888:8888"
        environment:
            LANG: en_US.utf8
            LC_ALL: en_US.utf8
        volumes:
            - ./:/src/cfgov-refresh
        entrypoint:
            - sh
            - /src/cfgov-refresh/docker/docs/entrypoint.sh
        working_dir: /src/cfgov-refresh
        stdin_open: true
        tty: true
